# CODSOFT TASK-2 SPAM SMS DETECTION

### IMPORTING PACKAGES

In [36]:



import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB



### READING DATASET

In [45]:

df = pd.read_csv("spam.csv")

### DETAIL PREPROCESSING

In [46]:

df


v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [47]:
df.columns

Index(['v1', 'v2'], dtype='object')

In [48]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
df.tail()

v1                                                 v2
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [50]:
df.shape

(5572, 2)

In [51]:
df.describe()

v1                      v2
count   5572                    5572
unique     2                    5157
top      ham  Sorry, I'll call later
freq    4825                      30

### INSPECTING DATA

In [56]:
df.groupby('v1').describe()

spam                                   
       count mean  std  min  25%  50%  75%  max
v1                                             
ham   4825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam   747.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

### CONVERSION INTO NUMERICAL VALUES AND PUTTING THEM INTO NEW COLUMN 'SPAM'

In [58]:

df['spam']=df['v1'].apply(lambda x:1 if x=='spam' else 0)

In [59]:
df

v1                                                 v2  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
...    ...                                                ...   ...
5567  spam  This is the 2nd time we have tried 2 contact u...     1
5568   ham               Will ü b going to esplanade fr home?     0
5569   ham  Pity, * was in mood for that. So...any other s...     0
5570   ham  The guy did some bitching but I acted like i'd...     0
5571   ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

### SPLITTING TEST SET AND TRAIN SET BY 0.25:0.75

In [66]:
x_train, x_test, y_train, y_test = train_test_split(df.v2, df.spam, test_size=0.25)

In [67]:
x_train.describe()

count                       4179
unique                      3922
top       Sorry, I'll call later
freq                          22
Name: v2, dtype: object

In [68]:
y_train.describe()

count    4179.000000
mean        0.135678
std         0.342488
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: spam, dtype: float64

### WORD COUNT IN MATRIX

In [72]:

cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [74]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### TRAINING THE MODEL

In [76]:

model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

### PRETESTING HAM MESSAGES

In [79]:

sms_ham = ["lets go and party"]
sms_ham_count = cv.transform(sms_ham)
model.predict(sms_ham_count)

array([0], dtype=int64)

### PRETESTING SPAM MESSAGES

In [86]:

sms_spam = ['click to gain reward']
sms_spam_count = cv.transform(sms_spam)
model.predict(sms_spam_count)

array([1], dtype=int64)

### TRAINING FINAL MODEL AND CHECKING ACCURACY

In [87]:

x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9842067480258435

### SAVING THE MODEL

In [89]:
import joblib as jb

In [93]:
jb.dump(model, 'spam_sms_detection')

['spam_sms_detection']

In [94]:
model = jb.load('spam_sms_detection')

In [95]:
df.columns

Index(['v1', 'v2', 'spam'], dtype='object')